<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="fr" xml:lang="fr"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>Méthodes d’analyse spatiale : un grand bol d’R - 4&nbsp; Méthodes de détection d’agrégats spatiaux et spatio-temporels</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./05-AnalyseReseau.html" rel="next">
<link href="./03-MethodesRepartitionPonctuelle.html" rel="prev">
<link href="./images/introduction/Couverture_16_01-01.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "Pas de résultats",
    "search-matching-documents-text": "documents trouvés",
    "search-copy-link-title": "Copier le lien vers la recherche",
    "search-hide-matches-text": "Cacher les correspondances additionnelles",
    "search-more-match-text": "correspondance de plus dans ce document",
    "search-more-matches-text": "correspondances de plus dans ce document",
    "search-clear-button-title": "Effacer",
    "search-detached-cancel-button-title": "Annuler",
    "search-submit-button-title": "Envoyer",
    "search-label": "Recherche"
  }
}</script><script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><link rel="stylesheet" href="css/quizlib.min.css">
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Basculer la barre latérale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./04-AgregatsSpatiaux.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Méthodes de détection d'agrégats spatiaux et spatio-temporels</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Basculer la barre latérale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Méthodes d’analyse spatiale : un grand bol d’R</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/SerieBoldR/MethodesAnalyseSpatiale" rel="" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Recherche"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Préface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./00-auteurs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">À propos des auteurs</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Partie 1. Données spatiales et R</span></span>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-ManipulationDonneesSpatiales.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Manipulation des données spatiales dans&nbsp;R</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Partie 2. Autocorrélation spatiale</span></span>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-Autocorrelation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Autocorrélation spatiale</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Partie 3. Méthodes de répartition ponctuelle et de détections d’agrégats spatiaux</span></span>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-MethodesRepartitionPonctuelle.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Méthodes de répartition ponctuelle</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-AgregatsSpatiaux.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Méthodes de détection d’agrégats spatiaux et spatio-temporels</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Partie 4. Analyses de données avec des réseaux de transport</span></span>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-AnalyseReseau.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Mesures d’accessibilité spatiale selon différents modes de transport</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-AnalyseReseauEvenements.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Analyses d’évènements localisés sur un réseau</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Partie 5. Régressions spatiales et classifications spatiales</span></span>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-RegressionSpatiales.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Introduction aux modèles de régression spatiale</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-ClassificationsSpatiales.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Méthodes de classification non supervisée spatiale</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Partie 6. Exercices et bibliographie</span></span>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-Exercices.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Correction des exercices</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bibliographie</span></a>
  </div>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table des matières</h2>
   
  <ul>
<li>
<a href="#sec-041" id="toc-sec-041" class="nav-link active" data-scroll-target="#sec-041"><span class="header-section-number">4.1</span> Agrégats d’entités spatiales ponctuelles</a>
  <ul class="collapse">
<li><a href="#sec-0411" id="toc-sec-0411" class="nav-link" data-scroll-target="#sec-0411"><span class="header-section-number">4.1.1</span> DBSCAN&nbsp;: agrégats spatiaux</a></li>
  <li><a href="#sec-0412" id="toc-sec-0412" class="nav-link" data-scroll-target="#sec-0412"><span class="header-section-number">4.1.2</span> ST-DBSCAN&nbsp;: agrégats spatio-temporels</a></li>
  <li><a href="#sec-0414" id="toc-sec-0414" class="nav-link" data-scroll-target="#sec-0414"><span class="header-section-number">4.1.3</span> Mise en œuvre dans R</a></li>
  </ul>
</li>
  <li>
<a href="#sec-042" id="toc-sec-042" class="nav-link" data-scroll-target="#sec-042"><span class="header-section-number">4.2</span> Méthodes de balayage de Kulldorff</a>
  <ul class="collapse">
<li><a href="#sec-0421" id="toc-sec-0421" class="nav-link" data-scroll-target="#sec-0421"><span class="header-section-number">4.2.1</span> Objectifs de la méthode, types d’analyses, de modèles et d’agrégats</a></li>
  <li><a href="#sec-0422" id="toc-sec-0422" class="nav-link" data-scroll-target="#sec-0422"><span class="header-section-number">4.2.2</span> Principes de base de la méthode</a></li>
  <li><a href="#sec-043" id="toc-sec-043" class="nav-link" data-scroll-target="#sec-043"><span class="header-section-number">4.2.3</span> Mise en œuvre dans R</a></li>
  </ul>
</li>
  <li><a href="#sec-044" id="toc-sec-044" class="nav-link" data-scroll-target="#sec-044"><span class="header-section-number">4.3</span> Quiz de révision du chapitre</a></li>
  <li><a href="#sec-045" id="toc-sec-045" class="nav-link" data-scroll-target="#sec-045"><span class="header-section-number">4.4</span> Exercices de révision</a></li>
  </ul><div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/SerieBoldR/MethodesAnalyseSpatiale/issues/new" class="toc-action">Signaler un problème ou<br>formuler une suggestion</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title"><span id="sec-chap04" class="quarto-section-identifier"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Méthodes de détection d’agrégats spatiaux et spatio-temporels</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header><p>Dans ce chapitre, nous abordons deux familles de méthodes de détection d’agrégats spatiaux et spatio-temporels qui s’appliquent à des géométries différentes&nbsp;: les méthodes de classification basées sur la densité des points (couche de points), principalement les algorithmes DBSCAN <span class="citation" data-cites="DBSCAN1996">(<a href="references.html#ref-DBSCAN1996" role="doc-biblioref">Ester et al. 1996</a>)</span> et ST-DBSCAN <span class="citation" data-cites="birant2007st">(<a href="references.html#ref-birant2007st" role="doc-biblioref">Birant et Kut 2007</a>)</span>, et les méthodes de balayage de Kulldorff <span class="citation" data-cites="kulldorff1997spatial">(<a href="references.html#ref-kulldorff1997spatial" role="doc-biblioref">1997</a>)</span> (couche polygonale).</p>
<div class="bloc_package">
<div class="bloc_package-header">
<div class="bloc_package-icon">

</div>
<p><strong>Liste des <em>packages</em> utilisés dans ce chapitre</strong></p>
</div>
<div class="bloc_package-body">
<ul>
<li>Pour importer et manipuler des fichiers géographiques&nbsp;:
<ul>
<li>
<code>sf</code> pour importer et manipuler des données vectorielles.</li>
<li>
<code>dplyr</code> pour manipuler les données.</li>
</ul>
</li>
<li>Pour construire des cartes et des graphiques&nbsp;:
<ul>
<li>
<code>tmap</code> pour les cartes.</li>
<li>
<code>ggplot2</code> pour construire des graphiques.</li>
</ul>
</li>
<li>
<code>dbscan</code> pour l’algorithme DBSCAN.</li>
<li>
<code>SpatialEpi</code> pour les méthodes de balayage de Kurlldoff.</li>
</ul>
</div>
</div>
<section id="sec-041" class="level2" data-number="4.1"><h2 data-number="4.1" class="anchored" data-anchor-id="sec-041">
<span class="header-section-number">4.1</span> Agrégats d’entités spatiales ponctuelles</h2>
<section id="sec-0411" class="level3" data-number="4.1.1"><h3 data-number="4.1.1" class="anchored" data-anchor-id="sec-0411">
<span class="header-section-number">4.1.1</span> DBSCAN&nbsp;: agrégats spatiaux</h3>
<div class="bloc_objectif">
<div class="bloc_objectif-header">
<div class="bloc_objectif-icon">

</div>
<p><strong>Pourquoi utiliser DBSCAN ?</strong></p>
</div>
<div class="bloc_objectif-body">
<p>Dans le chapitre précédent, portant sur les <em>méthodes de répartition ponctuelles</em>, nous avons abordé la méthode KDE permettant de cartographier la densité de points dans une maille régulière (<a href="03-MethodesRepartitionPonctuelle.html#sec-0342">section&nbsp;<span>3.4.2</span></a>). La carte de chaleur obtenue avec la KDE représente les valeurs de densité (variable continue) pour les pixels couvrant le territoire à l’étude.</p>
<p>Avec l’algorithme DBSCAN <span class="citation" data-cites="DBSCAN1996">(<a href="references.html#ref-DBSCAN1996" role="doc-biblioref">Ester et al. 1996</a>)</span>, l’objectif est différent&nbsp;: il s’agit d’<strong>identifier des agrégats spatiaux d’évènements ponctuels dans un territoire donné</strong> (par exemple, des cas de maladies, d’accidents, d’espèces fauniques ou végétales, de crimes, etc.). Autrement dit, il s’agit d’identifier plusieurs régions du territoire à l’étude dans lesquelles la densité de points est forte.</p>
<p>Concrètement, si la méthode KDE renvoie une variable continue pour l’ensemble du territoire, l’algorithme DBSCAN renvoie une variable qualitative uniquement pour les points du jeu de données.</p>
</div>
</div>
<section id="sec-04111" class="level4" data-number="4.1.1.1"><h4 data-number="4.1.1.1" class="anchored" data-anchor-id="sec-04111">
<span class="header-section-number">4.1.1.1</span> Fonctionnement de DBSCAN</h4>
<p>DBSCAN (<em><strong>D</strong>ensity-<strong>B</strong>ased <strong>S</strong>patial <strong>C</strong>lustering of <strong>A</strong>pplications with <strong>N</strong>oise</em>) est un algorithme de classification non supervisée qui regroupe des observations en fonction de <strong>leur densité</strong> dans un espace à deux, trois ou <em>n</em> dimensions <span class="citation" data-cites="DBSCAN1996">(<a href="references.html#ref-DBSCAN1996" role="doc-biblioref">Ester et al. 1996</a>)</span>. Comme pour toute autre méthode de classification non supervisée, ces dimensions sont des variables. Par conséquent, en appliquant DBSCAN sur les coordonnées géographiques d’entités ponctuelles 2D (<em>x</em>, <em>y</em>) ou 3D (<em>x</em>, <em>y</em>, <em>z</em>), nous classifions les points du jeu de données.</p>
<p>Prenons un jeu de données fictives (<a href="#fig-DonnesFictivesDBSCAN">figure&nbsp;<span>4.1</span></a>, a). À l’œil nu, nous identifions clairement cinq régions distinctes avec une forte densité de points et des zones de faible densité; ces dernières étant représentées par les points noirs avec DBSCAN (<a href="#fig-DonnesFictivesDBSCAN">figure&nbsp;<span>4.1</span></a>, b).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-DonnesFictivesDBSCAN" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="04-AgregatsSpatiaux_files/figure-html/fig-DonnesFictivesDBSCAN-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;4.1: Jeu de données fictives et classification DBSCAN avec cinq classes</figcaption></figure>
</div>
</div>
</div>
<p>L’intérêt majeur de l’algorithme DBSCAN est qu’il est basé sur la <strong>densité des points</strong> et non sur la <strong>distance entre les points</strong> comme les algorithmes classiques de classification non supervisée que sont les k-moyennes, k-médianes, k-médoïdes ou la classification ascendante hiérarchique. Tel qu’illustré à la <a href="#fig-AutresMethodesClassifNonSuperv">figure&nbsp;<span>4.2</span></a>, l’utilisation de la distance pour identifier cinq groupes de points renvoie des résultats peu convaincants. D’une part, tous les points appartiennent à une classe, sans séparer les régions de fortes et de faibles densités. D’autre part, les algorithmes classiques basés sur la distance ne parviennent pas à bien identifier les deux agrégats circulaires (bleu et rouge à la <a href="#fig-DonnesFictivesDBSCAN">figure&nbsp;<span>4.1</span></a>, b) et parfois linéaires (vert et mauve à la <a href="#fig-DonnesFictivesDBSCAN">figure&nbsp;<span>4.1</span></a>, b).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-AutresMethodesClassifNonSuperv" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="04-AgregatsSpatiaux_files/figure-html/fig-AutresMethodesClassifNonSuperv-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;4.2: Classification avec d’autres algorithmes basés sur la distance</figcaption></figure>
</div>
</div>
</div>
<p>L’algorithme DBSCAN comprend deux paramètres qui doivent être définis par la personne utilisatrice&nbsp;:</p>
<ul>
<li><p><strong>Le rayon de recherche</strong>, dénommé <span class="math inline">\(\epsilon\)</span> (epsilon), habituellement basé sur la distance euclidienne. Les distances de Manhattan ou réticulaires peuvent aussi être utilisées.</p></li>
<li><p><strong>Le nombre minimum de points</strong>, dénommé <span class="math inline">\(MinPts\)</span>, requis pour qu’un point, incluant lui-même, soit considéré comme un point central et appartienne à un agrégat, un regroupement (<em>cluster</em> en anglais).</p></li>
</ul>
<div class="bloc_notes">
<div class="bloc_notes-header">
<div class="bloc_notes-icon">

</div>
<p><strong>Avantage de DBSCAN&nbsp;: nul besoin de spécifier le nombre d’agrégats (<em>clusters</em>)!</strong></p>
</div>
<div class="bloc_notes-body">
<p>Comparativement à d’autres méthodes de classification non supervisées comme les k-moyennes, k-médianes et k-médoïdes, DBSCAN ne requiert pas de spécifier le nombre de classes à identifier dans le jeu de données. Autrement dit, appliqué à des géométries ponctuelles, l’algorithme DBSCAN détecte autant d’agrégats spatiaux que nécessaire en fonction des valeurs des deux paramètres (<span class="math inline">\(\epsilon\)</span> et <span class="math inline">\(MinPts\)</span>).</p>
</div>
</div>
<p>À la <a href="#fig-TypesPointsDBSCAN">figure&nbsp;<span>4.3</span></a>, nous appliquons l’algorithme DBSCAN à un semis de points avec un rayon de recherche de 500&nbsp;mètres (<span class="math inline">\(\epsilon=500\)</span>) et un nombre minimum de cinq points (<span class="math inline">\(MinPts = 5\)</span>). Dans un premier temps, l’algorithme distingue trois types de points&nbsp;:</p>
<ol type="1">
<li>Des <strong>points centraux</strong> (<em>core points</em> en anglais) qui ont au moins cinq points (incluant eux-mêmes) dans un rayon de 500&nbsp;mètres (points rouges).</li>
<li>Des <strong>points frontières</strong> (<em>border points</em>) qui ont moins de cinq points (incluant eux-mêmes) dans un rayon de 500&nbsp;mètres, mais qui sont inclus dans la zone tampon de 500&nbsp;mètres d’un point central (points bleus).</li>
<li>Des <strong>points aberrants</strong> (<em>noise points</em>) qui ont moins de cinq points (incluant eux-mêmes) dans un rayon de 500&nbsp;mètres et qui ne sont pas inclus dans la zone tampon d’un point central (points noirs).</li>
</ol>
<div id="fig-TypesPointsDBSCAN" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="images/Chap04/DbscanTypesPoints.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;4.3: Trois types de points identifiés par l’algorithme DBSCAN</figcaption></figure>
</div>
<p>Par la suite, les étapes de l’algorithme sont les suivantes&nbsp;:</p>
<ul>
<li>
<p><strong>Étape&nbsp;1.</strong> Formation du premier agrégat</p>
<ul>
<li><p>Nous tirons au hasard un point central et l’assignons au premier agrégat (groupe ou <em>cluster</em>).</p></li>
<li><p>Puis, les points compris dans la zone tampon du premier point central sont ajoutés à ce premier agrégat.</p></li>
<li><p>De façon itérative, nous étendons l’agrégat avec les points centraux ou frontières qui sont compris dans les zones tampons des points ajoutés précédemment.</p></li>
</ul>
</li>
<li>
<p><strong>Étape&nbsp;2.</strong> Formation d’autres agrégats</p>
<ul>
<li><p>Lorsque le premier agrégat est complété, nous tirons au hasard un autre point central n’appartenant pas au premier agrégat.</p></li>
<li><p>Nous appliquons la même démarche qu’à l’étape&nbsp;1 pour étendre et compléter cet autre agrégat.</p></li>
<li><p>Les deux sous-étapes ci-dessus sont répétées jusqu’à ce que tous les points centraux et frontières soient assignés à un agrégat.</p></li>
</ul>
</li>
</ul>
<p>Nous obtenons ainsi <em>k</em> agrégats (valeurs de 1 à <em>k</em>) tandis que les points aberrants sont affectés à la même classe (valeur de 0 habituellement). Appliqué au semis de points, DBSCAN a détecté deux agrégats et quatre points aberrants (<a href="#fig-ResultatsDBSCAN">figure&nbsp;<span>4.4</span></a>).</p>
<div id="fig-ResultatsDBSCAN" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="images/Chap04/DbscanResultats.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;4.4: Résultats de l’algorithme DBSCAN</figcaption></figure>
</div>
</section><section id="sec-04112" class="level4" data-number="4.1.1.2"><h4 data-number="4.1.1.2" class="anchored" data-anchor-id="sec-04112">
<span class="header-section-number">4.1.1.2</span> Sensibilité et optimisation des paramètres de DBSCAN</h4>
<p>Les résultats de l’algorithme de DBSCAN varient en fonction de ses deux paramètres, soit le rayon de recherche (<span class="math inline">\(\epsilon\)</span>) et le nombre minimum de points (<span class="math inline">\(MinPts\)</span>).</p>
<p>Concernant le paramètre <span class="math inline">\(\epsilon\)</span>, plus sa valeur est réduite, plus le nombre de points identifiés comme aberrants est important. Inversement, plus elle est grande, plus le nombre d’agrégats diminue. En guise d’illustration, faisons varier la valeur du rayon en maintenant à cinq le nombre minimum de points&nbsp;:</p>
<ul>
<li><p>Avec un rayon de 250&nbsp;mètres, cinq agrégats sont identifiés tandis que 29&nbsp;points sont considérés comme du bruit (<a href="#fig-VariationResultatsDBSCAN">figure&nbsp;<span>4.5</span></a>, a).</p></li>
<li><p>Avec un rayon de 500&nbsp;mètres, la solution est plus optimale avec deux agrégats et cinq points aberrants (<a href="#fig-VariationResultatsDBSCAN">figure&nbsp;<span>4.5</span></a>, b).</p></li>
<li><p>Avec un rayon de 1000&nbsp;mètres, deux agrégats sont aussi identifiés. Par contre, il ne reste plus qu’un point aberrant. Par conséquent, quatre points qui, à l’œil nu, sont très éloignés d’un agrégat y sont pourtant affectés (<a href="#fig-VariationResultatsDBSCAN">figure&nbsp;<span>4.5</span></a>, c).</p></li>
<li><p>Avec un rayon de 1500&nbsp;mètres, tous les points sont affectés à un et un seul agrégat (<a href="#fig-VariationResultatsDBSCAN">figure&nbsp;<span>4.5</span></a>, d).</p></li>
</ul>
<div id="fig-VariationResultatsDBSCAN" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="images/Chap04/DbscanResultatsVariation.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;4.5: Variations de résultats de l’algorithme DBSCAN selon la taille du rayon</figcaption></figure>
</div>
<p>Concernant le paramètre <span class="math inline">\(MinPts\)</span>, plusieurs stratégies ont été proposées pour fixer sa valeur&nbsp;:</p>
<ul>
<li>
<span class="math inline">\(MinPts \geq dim(D) + 1\)</span>, c’est-à-dire que sa valeur doit être minimalement égale au nombre de dimensions (variables) plus un du jeu de données.</li>
<li>
<span class="math inline">\(MinPts = dim(D) \times 2\)</span>, c’est-à-dire que le nombre de points devrait être égal à deux fois le nombre de dimensions du tableau <span class="citation" data-cites="sander1998density">(<a href="references.html#ref-sander1998density" role="doc-biblioref">Sander et al. 1998</a>)</span>.</li>
<li>
<span class="math inline">\(MinPts = 4\)</span> quand le jeu de données ne comprend que deux dimensions <span class="citation" data-cites="DBSCAN1996">(<a href="references.html#ref-DBSCAN1996" role="doc-biblioref">Ester et al. 1996</a>)</span>, soit un critère qui s’applique à des géométries ponctuelles 2D.</li>
</ul>
<p>Après avoir fixé le nombre minimal de points, nous pouvons optimiser la valeur du rayon de recherche de la façon suivante&nbsp;:</p>
<ul>
<li><p>Pour chacun des points, calculer la distance au <em>k</em><sup>ième</sup> point le plus proche.</p></li>
<li><p>Trier les valeurs obtenues pour construire un graphique en courbe.</p></li>
<li><p>Dans ce graphique, utiliser le <em>critère du coude</em> pour repérer la ou les valeurs signalant un décrochement dans la courbe. À la lecture de la <a href="#fig-KPlusProcheDbScan">figure&nbsp;<span>4.6</span></a>, les valeurs d’epsilon (<span class="math inline">\(\epsilon\)</span>) à retenir pourraient être 300, 350, 425 et 450&nbsp;mètres.</p></li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-KPlusProcheDbScan" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="04-AgregatsSpatiaux_files/figure-html/fig-KPlusProcheDbScan-1.png" class="img-fluid figure-img" style="width:65.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;4.6: Optimisation de la valeur d’epsilon</figcaption></figure>
</div>
</div>
</div>
<p>Si vous repérez plusieurs seuils de distance dans le graphique des distances au <em>k</em><sup>ième</sup> plus proche voisin, réalisez et comparez les résultats des DBSCAN avec ces valeurs d’epsilon. À la <a href="#fig-DbscanResultatsOptimatisationEpsilon">figure&nbsp;<span>4.7</span></a>, nous constatons que les résultats avec des seuils de 425 et 450&nbsp;mètres sont identiques et semblent optimaux. Par contre, la solution avec un rayon de 350&nbsp;mètres identifie deux points aberrants qui pourraient être intégrés au deuxième agrégat tandis que celle avec un rayon de 300&nbsp;mètres identifie un agrégat supplémentaire, mais classifie de nombreux points comme aberrants.</p>
<div class="bloc_attention">
<div class="bloc_attention-header">
<div class="bloc_attention-icon">

</div>
<p><strong>Quel résultat choisir parmi les quatre solutions?</strong></p>
</div>
<div class="bloc_attention-body">
<p>Comme pour toute analyse de classification, votre choix peut être objectif et reposer uniquement sur des indicateurs statistiques (ici, le graphique des distances au <em>k</em> plus proche voisin). Il devrait aussi s’appuyer sur vos connaissances du terrain. Par exemple, l’identification d’un troisième agrégat avec une valeur d’epsilon fixée à 300&nbsp;mètres pourrait refléter selon vous une réalité terrain particulièrement intéressante qui motiverait fortement le choix de cette solution.</p>
</div>
</div>
<div id="fig-DbscanResultatsOptimatisationEpsilon" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="images/Chap04/DbscanResultatsOptimatisationEpsilon.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;4.7: Comparaison de solutions DBSCAN avec différentes valeurs d’epsilon</figcaption></figure>
</div>
<div class="bloc_aller_loin">
<div class="bloc_aller_loin-header">
<div class="bloc_aller_loin-icon">

</div>
<p><strong>Autres algorithmes de classification non supervisée basée sur la densité</strong></p>
</div>
<div class="bloc_aller_loin-body">
<p>Bien que DBSCAN soit l’algorithme le plus utilisé, d’autres algorithmes basés sur la densité peuvent être utilisés pour détecter des agrégats spatiaux de points, notamment&nbsp;:</p>
<ul>
<li><p>HDBSCAN (<em><strong>H</strong>ierarchical <strong>D</strong>ensity-<strong>B</strong>ased <strong>S</strong>patial <strong>C</strong>lustering of <strong>A</strong>pplications with <strong>N</strong>oise</em>) <span class="citation" data-cites="HDBSCAN2013">(<a href="references.html#ref-HDBSCAN2013" role="doc-biblioref">Campello, Moulavi et Sander 2013</a>)</span>. Brièvement, cette version modifiée de DBSCAN permet d’obtenir une hiérarchie de partitions, comme dans une classification ascendante hiérarchique.</p></li>
<li><p>OPTICS (<em><strong>O</strong>rdering <strong>P</strong>oints <strong>T</strong>o <strong>I</strong>dentify the <strong>C</strong>lustering <strong>S</strong>tructure</em>) <span class="citation" data-cites="HDBSCAN2013">(<a href="references.html#ref-HDBSCAN2013" role="doc-biblioref">Campello, Moulavi et Sander 2013</a>)</span>. Avec OPTICS, la distance de voisinage (<span class="math inline">\(\epsilon\)</span>) n’a pas besoin d’être spécifiée. Succinctement, pour chaque point du jeu de données, il utilise la distance au <span class="math inline">\(k\)</span> (<span class="math inline">\(MinPts\)</span>) plus proche voisin.</p></li>
</ul>
<p><strong>Application à des évènements localisés sur un réseau de rues</strong></p>
<p>Lorsque les évènements sont localisés sur un réseau de rues (des accidents par exemple), il convient d’utiliser une autre métrique que la distance euclidienne pour le rayon de recherche (<span class="math inline">\(\epsilon\)</span>), soit la distance du chemin le plus court à travers le réseau de rues, ce que nous verrons au chapitre suivant (<a href="06-AnalyseReseauEvenements.html#sec-064">section&nbsp;<span>6.4</span></a>). Geoff Boeing a aussi proposé un <a href="https://geoffboeing.com/2018/04/network-based-spatial-clustering/">un code Python</a> basé sur la librairie <a href="https://geoffboeing.com/2016/11/osmnx-python-street-networks/">OSMnx</a>.</p>
</div>
</div>
</section></section><section id="sec-0412" class="level3" data-number="4.1.2"><h3 data-number="4.1.2" class="anchored" data-anchor-id="sec-0412">
<span class="header-section-number">4.1.2</span> ST-DBSCAN&nbsp;: agrégats spatio-temporels</h3>
<p>Derya Birant et Alp Kut <span class="citation" data-cites="birant2007st">(<a href="references.html#ref-birant2007st" role="doc-biblioref">2007</a>)</span> ont proposé une modification de l’algorithme de DBSCAN afin qu’il puisse s’appliquer à des données spatio-temporelles (<span class="math inline">\(x\)</span>, <span class="math inline">\(y\)</span>, <span class="math inline">\(d\)</span>) avec <span class="math inline">\(d\)</span> étant la date de l’évènement. Dénommé ST-DBSCAN, l’algorithme comprend toujours les deux paramètres de DBSCAN (<span class="math inline">\(MinPts\)</span> et <span class="math inline">\(\epsilon\)</span>), auxquels s’ajoute un autre paramètre <span class="math inline">\(\epsilon\)</span> pour le temps (défini en heure, jour, semaine, mois ou année). Autrement dit, deux paramètres de distance sont utilisés&nbsp;: <span class="math inline">\(\epsilon_1\)</span> pour la proximité spatiale (comme avec DBSCAN) et <span class="math inline">\(\epsilon_2\)</span> pour la proximité temporelle <span class="citation" data-cites="birant2007st">(<a href="references.html#ref-birant2007st" role="doc-biblioref">Birant et Kut 2007</a>)</span>. De la sorte, deux points sont considérés comme voisins si la distance spatiale et la distance temporelle sont toutes deux inférieures aux seuils fixés.</p>
<div class="bloc_attention">
<div class="bloc_attention-header">
<div class="bloc_attention-icon">

</div>
<p><strong>Fenêtre temporelle des points formant un agrégat</strong></p>
</div>
<div class="bloc_attention-body">
<p>Attention, les points formant un agrégat peuvent avoir une fenêtre temporelle bien plus grande que le seuil <span class="math inline">\(\epsilon_2\)</span> fixé. Par exemple, fixons les valeurs de <span class="math inline">\(\epsilon_1\)</span> à 500&nbsp;mètres et de <span class="math inline">\(\epsilon_2\)</span> à 7&nbsp;jours. Si le point&nbsp;A (<span class="math inline">\(d\)</span>&nbsp;=&nbsp;2023-01-15) est distant de 400&nbsp;mètres du point&nbsp;B (<span class="math inline">\(d\)</span>&nbsp;=&nbsp;2023-01-20), les deux points sont considérés comme voisins. Par contre, si le point&nbsp;B est distant du point&nbsp;C (<span class="math inline">\(d\)</span>&nbsp;=&nbsp;2023-01-25) de moins de 500&nbsp;mètres, il peut être aussi agrégé à l’agrégat puisque l’écart temporel entre B et C est de 5&nbsp;jours.</p>
<p>Habituellement, plus la valeur de <span class="math inline">\(\epsilon_2\)</span> est faible, plus le nombre de points considérés comme aberrants est important.</p>
</div>
</div>
</section><section id="sec-0414" class="level3" data-number="4.1.3"><h3 data-number="4.1.3" class="anchored" data-anchor-id="sec-0414">
<span class="header-section-number">4.1.3</span> Mise en œuvre dans R</h3>
<section id="sec-04141" class="level4" data-number="4.1.3.1"><h4 data-number="4.1.3.1" class="anchored" data-anchor-id="sec-04141">
<span class="header-section-number">4.1.3.1</span> DBSCAN</h4>
<p>Nous utilisons le <em>package</em> <code>dbscan</code> <span class="citation" data-cites="dbscanPackage1 dbscanPackage2">(<a href="references.html#ref-dbscanPackage1" role="doc-biblioref">Hahsler et Piekenbrock 2022</a>; <a href="references.html#ref-dbscanPackage2" role="doc-biblioref">Hahsler, Piekenbrock et Doran 2019</a>)</span> dans lequel sont implémentés plusieurs algorithmes, dont DBSCAN, mais aussi OPTICS et HDBSCAN. La fonction <code>dbscan(x, eps, minPts, weights = NULL)</code> comprend plusieurs paramètres&nbsp;:</p>
<ul>
<li>
<code>x</code>: une matrice, un <em>DataFrame</em>, un objet <code>dist</code> ou un objet <code>frNN</code>.</li>
<li>
<code>eps</code>: le rayon de recherche epsilon (<span class="math inline">\(\epsilon\)</span>).</li>
<li>
<code>minPts</code>: le nombre de points minimum requis pour que chaque point soit considéré comme un point central.</li>
<li>
<code>weights</code>: un vecteur numérique optionnel pour pondérer les points.</li>
</ul>
<p>Pour illustrer le fonctionnement de la méthode DBSCAN, nous avons extrait les accidents d’un <a href="https://donneesouvertes-sherbrooke.opendata.arcgis.com/datasets/64d19d62f0804f5896e4b24c32aea49d_0/explore?location=45.403675%2C-71.960143%2C12.65">jeu de données sur les incidents de sécurité publique survenus sur le territoire de la Ville de Sherbrooke de juillet 2019 à juin 2022</a> (<a href="#fig-CartoAccidents">figure&nbsp;<span>4.8</span></a>).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-CartoAccidents" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="04-AgregatsSpatiaux_files/figure-html/fig-CartoAccidents-1.png" class="img-fluid figure-img" style="width:65.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;4.8: Accidents survenus entre juillet 2019 et juin 2022, Ville de Sherbrooke</figcaption></figure>
</div>
</div>
</div>
<p>Dans le code ci-dessous, nous réalisons trois étapes préalables au calcul de DBSCAN&nbsp;:</p>
<ul>
<li>Importation des accidents.</li>
<li>Récupération des coordonnées (<span class="math inline">\(x\)</span>, <span class="math inline">\(y\)</span>) des accidents et stockage dans une matrice.</li>
<li>Construction du graphique à partir de la distance au quatrième point le plus proche.</li>
</ul>
<p>Nous n’observons pas de décrochement particulier dans la courbe de la <a href="#fig-GraphiqueAccidentsDist4">figure&nbsp;<span>4.9</span></a>. Par conséquent, nous pourrions tout aussi bien retenir une distance euclidienne de 250, 500, 1000 ou 1500&nbsp;mètres pour epsilon.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://r-spatial.github.io/sf/">sf</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/mtennekes/tmap">tmap</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/mhahsler/dbscan">dbscan</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ggplot2.tidyverse.org">ggplot2</a></span><span class="op">)</span></span>
<span><span class="co">## Importation des accidents</span></span>
<span><span class="va">Accidents.sf</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_read.html">st_read</a></span><span class="op">(</span>dsn <span class="op">=</span> <span class="st">"data/chap04/DataAccidentsSherb.shp"</span>, quiet<span class="op">=</span><span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="co">## Coordonnées géographiques</span></span>
<span><span class="va">xy</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_coordinates.html">st_coordinates</a></span><span class="op">(</span><span class="va">Accidents.sf</span><span class="op">)</span></span>
<span><span class="co">## Graphique pour la distance au quatrième voisin le plus proche</span></span>
<span><span class="va">DistKplusproche</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/dbscan/man/kNNdist.html">kNNdist</a></span><span class="op">(</span><span class="va">xy</span>, k <span class="op">=</span> <span class="fl">4</span><span class="op">)</span></span>
<span><span class="va">DistKplusproche</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/as.data.frame.html">as.data.frame</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/sort.html">sort</a></span><span class="op">(</span><span class="va">DistKplusproche</span>, decreasing <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">DistKplusproche</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="st">"distance"</span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">DistKplusproche</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_path</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="fl">1</span><span class="op">:</span><span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">DistKplusproche</span><span class="op">)</span>, y <span class="op">=</span> <span class="va">distance</span><span class="op">)</span>, size<span class="op">=</span><span class="fl">1</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Points triés par ordre croissant selon la distance"</span>,</span>
<span>       y <span class="op">=</span> <span class="st">"Distance au quatrième point le plus proche"</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_hline</a></span><span class="op">(</span>yintercept<span class="op">=</span><span class="fl">250</span>, color <span class="op">=</span> <span class="st">"#08306b"</span>, linetype<span class="op">=</span><span class="st">"dashed"</span>, size<span class="op">=</span><span class="fl">1</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_hline</a></span><span class="op">(</span>yintercept<span class="op">=</span><span class="fl">500</span>, color <span class="op">=</span> <span class="st">"#00441b"</span>, linetype<span class="op">=</span><span class="st">"dashed"</span>, size<span class="op">=</span><span class="fl">1</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_hline</a></span><span class="op">(</span>yintercept<span class="op">=</span><span class="fl">1000</span>, color <span class="op">=</span> <span class="st">"#67000d"</span>, linetype<span class="op">=</span><span class="st">"dashed"</span>, size<span class="op">=</span><span class="fl">1</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_hline</a></span><span class="op">(</span>yintercept<span class="op">=</span><span class="fl">1500</span>, color <span class="op">=</span> <span class="st">"#3f007d"</span>, linetype<span class="op">=</span><span class="st">"dashed"</span>, size<span class="op">=</span><span class="fl">1</span><span class="op">)</span></span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-GraphiqueAccidentsDist4" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="04-AgregatsSpatiaux_files/figure-html/fig-GraphiqueAccidentsDist4-1.png" class="img-fluid figure-img" style="width:65.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;4.9: Optimisation de la valeur d’epsilon pour les accidents</figcaption></figure>
</div>
</div>
</div>
<p>Appliquons la méthode DBSCAN avec un minimum de quatre points et les quatre valeurs de distance euclidienne.</p>
<div class="cell">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">123456789</span><span class="op">)</span></span>
<span><span class="co">## DBSCAN avec les quatre distances</span></span>
<span><span class="va">dbscan250</span>  <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/dbscan/man/dbscan.html">dbscan</a></span><span class="op">(</span><span class="va">xy</span>, eps <span class="op">=</span> <span class="fl">250</span>, minPts <span class="op">=</span> <span class="fl">4</span><span class="op">)</span></span>
<span><span class="va">dbscan500</span>  <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/dbscan/man/dbscan.html">dbscan</a></span><span class="op">(</span><span class="va">xy</span>, eps <span class="op">=</span> <span class="fl">500</span>, minPts <span class="op">=</span> <span class="fl">4</span><span class="op">)</span></span>
<span><span class="va">dbscan1000</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/dbscan/man/dbscan.html">dbscan</a></span><span class="op">(</span><span class="va">xy</span>, eps <span class="op">=</span> <span class="fl">1000</span>, minPts <span class="op">=</span> <span class="fl">4</span><span class="op">)</span></span>
<span><span class="va">dbscan1500</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/dbscan/man/dbscan.html">dbscan</a></span><span class="op">(</span><span class="va">xy</span>, eps <span class="op">=</span> <span class="fl">1500</span>, minPts <span class="op">=</span> <span class="fl">4</span><span class="op">)</span></span>
<span><span class="co">## Affichage des résultats</span></span>
<span><span class="va">dbscan250</span></span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>DBSCAN clustering for 1106 objects.
Parameters: eps = 250, minPts = 4
Using euclidean distances and borderpoints = TRUE
The clustering contains 45 cluster(s) and 353 noise points.

  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19 
353   4   6   7   5  15   5   4  22   7   5   5  19 295   4  18   5   4   7   8 
 20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39 
  4   6  49   4  11   4   4  41   5   4   8  31  25  10   6  23   4   5  18  15 
 40  41  42  43  44  45 
  6   4   6   4   7   4 

Available fields: cluster, eps, minPts, dist, borderPoints</code></pre>
</div>
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">dbscan500</span></span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>DBSCAN clustering for 1106 objects.
Parameters: eps = 500, minPts = 4
Using euclidean distances and borderpoints = TRUE
The clustering contains 33 cluster(s) and 143 noise points.

  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19 
143   7   6  14   4   5   5   4   6 734  18   8   6   6   5   9  16   9   5   4 
 20  21  22  23  24  25  26  27  28  29  30  31  32  33 
 23   5   3   4   6   5   4   9   6   9   4   4   4   6 

Available fields: cluster, eps, minPts, dist, borderPoints</code></pre>
</div>
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">dbscan1000</span></span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>DBSCAN clustering for 1106 objects.
Parameters: eps = 1000, minPts = 4
Using euclidean distances and borderpoints = TRUE
The clustering contains 10 cluster(s) and 42 noise points.

  0   1   2   3   4   5   6   7   8   9  10 
 42   8   6  37 962   8   4   6   5  12  16 

Available fields: cluster, eps, minPts, dist, borderPoints</code></pre>
</div>
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">dbscan1500</span></span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>DBSCAN clustering for 1106 objects.
Parameters: eps = 1500, minPts = 4
Using euclidean distances and borderpoints = TRUE
The clustering contains 3 cluster(s) and 7 noise points.

   0    1    2    3 
   7 1047   12   40 

Available fields: cluster, eps, minPts, dist, borderPoints</code></pre>
</div>
</div>
<p>Pour les 1106&nbsp;accidents du jeu de données, les résultats des quatre DBSCAN ci-dessus sont les suivants&nbsp;:</p>
<ul>
<li>Avec <span class="math inline">\(\epsilon = 250\)</span>, 45&nbsp;agrégats et 353&nbsp;points aberrants (bruit).</li>
<li>Avec <span class="math inline">\(\epsilon = 500\)</span>, 33&nbsp;agrégats et 143&nbsp;points aberrants.</li>
<li>Avec <span class="math inline">\(\epsilon = 1000\)</span>, 10&nbsp;agrégats et 42&nbsp;points aberrants.</li>
<li>Avec <span class="math inline">\(\epsilon = 1500\)</span>, 3&nbsp;agrégats et 7&nbsp;points aberrants.</li>
</ul>
<p>Pour les <em>n</em> points du jeu de données, l’appartenance à un agrégat est enregistrée dans un vecteur numérique avec des valeurs de 0 à <em>k</em> agrégats (<code>ResultatDbscan$cluster</code>). Notez que la valeur de 0 est attribuée aux points aberrants. Avec ce vecteur, nous enregistrons les résultats dans un nouveau champ de la couche de points <code>sf</code>.</p>
<div class="cell">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">## Enregistrement des résultats de DBSCAN dans la couche de points sf</span></span>
<span><span class="va">Accidents.sf</span><span class="op">$</span><span class="va">Dbscan250</span>  <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/character.html">as.character</a></span><span class="op">(</span><span class="va">dbscan250</span><span class="op">$</span><span class="va">cluster</span><span class="op">)</span></span>
<span><span class="va">Accidents.sf</span><span class="op">$</span><span class="va">Dbscan500</span>  <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/character.html">as.character</a></span><span class="op">(</span><span class="va">dbscan500</span><span class="op">$</span><span class="va">cluster</span><span class="op">)</span></span>
<span><span class="va">Accidents.sf</span><span class="op">$</span><span class="va">Dbscan1000</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/character.html">as.character</a></span><span class="op">(</span><span class="va">dbscan1000</span><span class="op">$</span><span class="va">cluster</span><span class="op">)</span></span>
<span><span class="va">Accidents.sf</span><span class="op">$</span><span class="va">Dbscan1500</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/character.html">as.character</a></span><span class="op">(</span><span class="va">dbscan1500</span><span class="op">$</span><span class="va">cluster</span><span class="op">)</span></span>
<span></span>
<span><span class="va">Accidents.sf</span><span class="op">$</span><span class="va">Dbscan250</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/nchar.html">nchar</a></span><span class="op">(</span><span class="va">Accidents.sf</span><span class="op">$</span><span class="va">Dbscan250</span><span class="op">)</span> <span class="op">==</span> <span class="fl">1</span>,</span>
<span>                                        <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">"0"</span>, <span class="va">Accidents.sf</span><span class="op">$</span><span class="va">Dbscan250</span><span class="op">)</span>,</span>
<span>                                        <span class="va">Accidents.sf</span><span class="op">$</span><span class="va">Dbscan250</span><span class="op">)</span></span>
<span><span class="va">Accidents.sf</span><span class="op">$</span><span class="va">Dbscan500</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/nchar.html">nchar</a></span><span class="op">(</span><span class="va">Accidents.sf</span><span class="op">$</span><span class="va">Dbscan500</span><span class="op">)</span> <span class="op">==</span> <span class="fl">1</span>,</span>
<span>                                        <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">"0"</span>, <span class="va">Accidents.sf</span><span class="op">$</span><span class="va">Dbscan500</span><span class="op">)</span>,</span>
<span>                                        <span class="va">Accidents.sf</span><span class="op">$</span><span class="va">Dbscan500</span><span class="op">)</span></span>
<span><span class="va">Accidents.sf</span><span class="op">$</span><span class="va">Dbscan1000</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/nchar.html">nchar</a></span><span class="op">(</span><span class="va">Accidents.sf</span><span class="op">$</span><span class="va">Dbscan1000</span><span class="op">)</span> <span class="op">==</span> <span class="fl">1</span>,</span>
<span>                                        <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">"0"</span>, <span class="va">Accidents.sf</span><span class="op">$</span><span class="va">Dbscan1000</span><span class="op">)</span>,</span>
<span>                                        <span class="va">Accidents.sf</span><span class="op">$</span><span class="va">Dbscan1000</span><span class="op">)</span></span>
<span><span class="va">Accidents.sf</span><span class="op">$</span><span class="va">Dbscan1500</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/nchar.html">nchar</a></span><span class="op">(</span><span class="va">Accidents.sf</span><span class="op">$</span><span class="va">Dbscan1500</span><span class="op">)</span> <span class="op">==</span> <span class="fl">1</span>,</span>
<span>                                        <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">"0"</span>, <span class="va">Accidents.sf</span><span class="op">$</span><span class="va">Dbscan1500</span><span class="op">)</span>,</span>
<span>                                        <span class="va">Accidents.sf</span><span class="op">$</span><span class="va">Dbscan1500</span><span class="op">)</span></span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Nous cartographions finalement les résultats pour les quatre solutions.</p>
<div class="cell">
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tmap_mode.html">tmap_mode</a></span><span class="op">(</span><span class="st">"plot"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_shape.html">tm_shape</a></span><span class="op">(</span><span class="va">Accidents.sf</span><span class="op">)</span><span class="op">+</span><span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_symbols.html">tm_dots</a></span><span class="op">(</span>col<span class="op">=</span><span class="st">"Dbscan250"</span>, title <span class="op">=</span> <span class="st">"DBSCAN 250"</span>, size <span class="op">=</span> <span class="fl">.5</span><span class="op">)</span></span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="04-AgregatsSpatiaux_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_shape.html">tm_shape</a></span><span class="op">(</span><span class="va">Accidents.sf</span><span class="op">)</span><span class="op">+</span><span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_symbols.html">tm_dots</a></span><span class="op">(</span>col<span class="op">=</span><span class="st">"Dbscan500"</span>, title <span class="op">=</span> <span class="st">"DBSCAN 500"</span>, size <span class="op">=</span> <span class="fl">.5</span><span class="op">)</span></span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="04-AgregatsSpatiaux_files/figure-html/unnamed-chunk-9-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_shape.html">tm_shape</a></span><span class="op">(</span><span class="va">Accidents.sf</span><span class="op">)</span><span class="op">+</span><span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_symbols.html">tm_dots</a></span><span class="op">(</span>col<span class="op">=</span><span class="st">"Dbscan1000"</span>, title <span class="op">=</span> <span class="st">"DBSCAN 1000"</span>, size <span class="op">=</span> <span class="fl">.5</span><span class="op">)</span></span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="04-AgregatsSpatiaux_files/figure-html/unnamed-chunk-9-3.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_shape.html">tm_shape</a></span><span class="op">(</span><span class="va">Accidents.sf</span><span class="op">)</span><span class="op">+</span><span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_symbols.html">tm_dots</a></span><span class="op">(</span>col<span class="op">=</span><span class="st">"Dbscan1500"</span>, title <span class="op">=</span> <span class="st">"DBSCAN 1500"</span>, size <span class="op">=</span> <span class="fl">.5</span><span class="op">)</span></span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="04-AgregatsSpatiaux_files/figure-html/unnamed-chunk-9-4.png" class="img-fluid" width="672"></p>
</div>
</div>
</section><section id="sec-04142" class="level4" data-number="4.1.3.2"><h4 data-number="4.1.3.2" class="anchored" data-anchor-id="sec-04142">
<span class="header-section-number">4.1.3.2</span> ST-DBSCAN</h4>
<p>Pour l’algorithme ST-DBSCAN, nous utilisons une <a href="https://github.com/CKerouanton/ST-DBSCAN/blob/master/stdbscan.R">fonction R</a> proposée par Colin Kerouanton.</p>
<div class="cell">
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/source.html">source</a></span><span class="op">(</span><span class="st">"code_complementaire/stdbscan.R"</span><span class="op">)</span></span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Calculons ST-DBSCAN avec une distance spatiale de 1000&nbsp;mètres et une distance temporelle de 21&nbsp;jours. Nous obtenons 26&nbsp;agrégats et 584&nbsp;points identifiés comme aberrants.</p>
<div class="cell">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">## Importation des accidents</span></span>
<span><span class="va">Accidents.sf</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_read.html">st_read</a></span><span class="op">(</span>dsn <span class="op">=</span> <span class="st">"data/chap04/DataAccidentsSherb.shp"</span>, quiet<span class="op">=</span><span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="co">## Coordonnées géographiques</span></span>
<span><span class="va">xy</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_coordinates.html">st_coordinates</a></span><span class="op">(</span><span class="va">Accidents.sf</span><span class="op">)</span></span>
<span><span class="va">Accidents.sf</span><span class="op">$</span><span class="va">x</span> <span class="op">&lt;-</span> <span class="va">xy</span><span class="op">[</span>,<span class="fl">1</span><span class="op">]</span></span>
<span><span class="va">Accidents.sf</span><span class="op">$</span><span class="va">y</span> <span class="op">&lt;-</span> <span class="va">xy</span><span class="op">[</span>,<span class="fl">2</span><span class="op">]</span></span>
<span><span class="co">## Vérifions que le champ DATEINCIDE est bien au format date</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/str.html">str</a></span><span class="op">(</span><span class="va">Accidents.sf</span><span class="op">$</span><span class="va">DATEINCIDE</span><span class="op">)</span></span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Date[1:1106], format: "2021-12-11" "2022-05-16" "2021-08-12" "2019-08-02" "2020-03-02" ...</code></pre>
</div>
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">## Calcul de st-dbscan avec une distance de 1000 mètres et 21 jours</span></span>
<span><span class="va">Resultats.stdbscan</span> <span class="op">&lt;-</span> <span class="fu">stdbscan</span><span class="op">(</span>x <span class="op">=</span> <span class="va">Accidents.sf</span><span class="op">$</span><span class="va">x</span>,</span>
<span>                              y <span class="op">=</span> <span class="va">Accidents.sf</span><span class="op">$</span><span class="va">y</span>,</span>
<span>                              time <span class="op">=</span> <span class="va">Accidents.sf</span><span class="op">$</span><span class="va">DATEINCIDE</span>,</span>
<span>                              eps1 <span class="op">=</span> <span class="fl">1000</span>,</span>
<span>                              eps2 <span class="op">=</span> <span class="fl">21</span>,</span>
<span>                              minpts <span class="op">=</span> <span class="fl">4</span><span class="op">)</span></span>
<span><span class="co">## Enregistrement des résultats de ST-DBSCAN dans la couche de points sf</span></span>
<span><span class="va">Accidents.sf</span><span class="op">$</span><span class="va">stdbscan.1000_21</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/character.html">as.character</a></span><span class="op">(</span><span class="va">Resultats.stdbscan</span><span class="op">$</span><span class="va">cluster</span><span class="op">)</span></span>
<span><span class="va">Accidents.sf</span><span class="op">$</span><span class="va">stdbscan.1000_21</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/nchar.html">nchar</a></span><span class="op">(</span><span class="va">Accidents.sf</span><span class="op">$</span><span class="va">stdbscan.1000_21</span><span class="op">)</span> <span class="op">==</span> <span class="fl">1</span>,</span>
<span>                                        <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">"0"</span>, <span class="va">Accidents.sf</span><span class="op">$</span><span class="va">stdbscan.1000_21</span><span class="op">)</span>,</span>
<span>                                        <span class="va">Accidents.sf</span><span class="op">$</span><span class="va">stdbscan.1000_21</span><span class="op">)</span></span>
<span><span class="co">## Nombre de points par agrégat</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">Accidents.sf</span><span class="op">$</span><span class="va">stdbscan.1000_21</span><span class="op">)</span></span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 00  01  02  03  04  05  06  07  08  09  10  11  12  13  14  15  16  17  18  19 
584   4   6   5   4   4   7   7   4 178 156  13  17   4  22  32   6   7   8   8 
 20  21  22  23  24  25  26 
  5   6   4   3   5   4   3 </code></pre>
</div>
</div>
<p>Pour faciliter l’analyse des résultats de ST-DBSCAN, nous conseillons de&nbsp;:</p>
<ol type="1">
<li>Construire un tableau récapitulatif pour les agrégats avec le nombre de points, les dates de début et de fin et l’intervalle temporel.</li>
<li>Construire un graphique avec les agrégats (axe des <em>y</em>) et la dimension temporelle (axe des <em>x</em>).</li>
<li>Cartographier les résultats.</li>
</ol>
<p>Le code ci-dessous génère le tableau récapitulatif. Nous constatons ainsi que les agrégats 9 et 10 incluent respectivement 178 et 156&nbsp;points avec des intervalles temporels importants (respectivement 251 et 319&nbsp;jours).</p>
<div class="cell">
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://dplyr.tidyverse.org">dplyr</a></span><span class="op">)</span></span>
<span><span class="co">## Sélection des points appartenant à un agrégat</span></span>
<span><span class="va">Agregats</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/subset.html">subset</a></span><span class="op">(</span><span class="va">Accidents.sf</span>, </span>
<span>                   <span class="va">Accidents.sf</span><span class="op">$</span><span class="va">stdbscan.1000_21</span> <span class="op">!=</span> <span class="st">"00"</span><span class="op">)</span></span>
<span><span class="co">## Conversion de la date au format POSIXct</span></span>
<span><span class="va">Agregats</span><span class="op">$</span><span class="va">dtPOSIXct</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/as.POSIXlt.html">as.POSIXct</a></span><span class="op">(</span><span class="va">Agregats</span><span class="op">$</span><span class="va">DATEINCIDE</span>, format <span class="op">=</span> <span class="st">"%Y/%m/%d"</span><span class="op">)</span></span>
<span><span class="co">## Tableau récapitulatif</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="st"><a href="https://dplyr.tidyverse.org">"dplyr"</a></span><span class="op">)</span>  </span>
<span><span class="va">Tableau.stdbscan</span> <span class="op">&lt;-</span></span>
<span>    <span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_geometry.html">st_drop_geometry</a></span><span class="op">(</span><span class="va">Agregats</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>      <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">stdbscan.1000_21</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>      <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarize</a></span><span class="op">(</span>points <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html">n</a></span><span class="op">(</span><span class="op">)</span>,</span>
<span>                date.min <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">min</a></span><span class="op">(</span><span class="va">DATEINCIDE</span><span class="op">)</span>,</span>
<span>                date.max <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">max</a></span><span class="op">(</span><span class="va">DATEINCIDE</span><span class="op">)</span>,</span>
<span>                intervalle.jours <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">max</a></span><span class="op">(</span><span class="va">DATEINCIDE</span><span class="op">)</span><span class="op">-</span><span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">min</a></span><span class="op">(</span><span class="va">DATEINCIDE</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">## Affichage du tableau</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">Tableau.stdbscan</span>, n <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">Tableau.stdbscan</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 26 × 5
   stdbscan.1000_21 points date.min   date.max   intervalle.jours
   &lt;chr&gt;             &lt;int&gt; &lt;date&gt;     &lt;date&gt;                &lt;dbl&gt;
 1 01                    4 2019-08-08 2019-09-04               27
 2 02                    6 2021-12-15 2022-01-25               41
 3 03                    5 2019-07-21 2019-08-30               40
 4 04                    4 2020-11-10 2020-12-12               32
 5 05                    4 2022-01-08 2022-02-13               36
 6 06                    7 2021-06-09 2021-07-02               23
 7 07                    7 2020-06-23 2020-08-07               45
 8 08                    4 2021-09-30 2021-10-27               27
 9 09                  178 2019-07-02 2020-03-09              251
10 10                  156 2021-03-13 2022-01-26              319
11 11                   13 2021-07-24 2021-09-11               49
12 12                   17 2021-10-21 2022-01-12               83
13 13                    4 2021-06-16 2021-07-07               21
14 14                   22 2022-04-11 2022-06-27               77
15 15                   32 2020-09-11 2020-12-18               98
16 16                    6 2020-01-17 2020-02-08               22
17 17                    7 2022-05-07 2022-05-30               23
18 18                    8 2021-04-01 2021-05-27               56
19 19                    8 2020-07-15 2020-09-11               58
20 20                    5 2019-07-05 2019-07-31               26
21 21                    6 2022-01-15 2022-03-02               46
22 22                    4 2020-06-17 2020-06-30               13
23 23                    3 2022-03-12 2022-03-18                6
24 24                    5 2021-06-29 2021-07-21               22
25 25                    4 2021-09-20 2021-10-25               35
26 26                    3 2021-04-13 2021-04-26               13</code></pre>
</div>
</div>
<p>La <a href="#fig-GraphStScanEps1000Eps21">figure&nbsp;<span>4.10</span></a> présente les points et l’étendue temporelle de chaque agrégat.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">## Construction du graphique</span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">Agregats</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">dtPOSIXct</span>, </span>
<span>                 y <span class="op">=</span> <span class="va">stdbscan.1000_21</span>, </span>
<span>                 color <span class="op">=</span> <span class="va">stdbscan.1000_21</span><span class="op">)</span>,</span>
<span>             show.legend <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_date.html">scale_x_datetime</a></span><span class="op">(</span>date_labels <span class="op">=</span> <span class="st">"%Y/%m"</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x<span class="op">=</span> <span class="st">"Temps"</span>,</span>
<span>       y<span class="op">=</span> <span class="st">"Identifiant de l'agrégat"</span>,</span>
<span>       title <span class="op">=</span> <span class="st">"ST-DBSCAN avec Esp1 = 1000, Esp2 = 21 et MinPts = 4"</span><span class="op">)</span></span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-GraphStScanEps1000Eps21" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="04-AgregatsSpatiaux_files/figure-html/fig-GraphStScanEps1000Eps21-1.png" class="img-fluid figure-img" style="width:65.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;4.10: Intervalles temporels des agrégats ST-DBSCAN</figcaption></figure>
</div>
</div>
</div>
<p>La cartographie des agrégats est présentée à la <a href="#fig-CarteStScanEps1000Eps21">figure&nbsp;<span>4.11</span></a> avec en noir les points aberrants.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">## Création de deux couches : l'une pour les agrégats, l'autre pour les points aberrants</span></span>
<span><span class="va">stdbcan.Agregats</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/subset.html">subset</a></span><span class="op">(</span><span class="va">Accidents.sf</span>, <span class="va">Accidents.sf</span><span class="op">$</span><span class="va">stdbscan.1000_21</span> <span class="op">!=</span> <span class="st">"00"</span><span class="op">)</span></span>
<span><span class="va">stdbcan.Bruit</span>    <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/subset.html">subset</a></span><span class="op">(</span><span class="va">Accidents.sf</span>, <span class="va">Accidents.sf</span><span class="op">$</span><span class="va">stdbscan.1000_21</span> <span class="op">==</span> <span class="st">"00"</span><span class="op">)</span></span>
<span><span class="co">## Cartographie</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tmap_mode.html">tmap_mode</a></span><span class="op">(</span><span class="st">"plot"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_shape.html">tm_shape</a></span><span class="op">(</span><span class="va">Arrondiss</span><span class="op">)</span><span class="op">+</span><span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_polygons.html">tm_fill</a></span><span class="op">(</span>col<span class="op">=</span><span class="st">"#f7f7f7"</span><span class="op">)</span><span class="op">+</span><span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_polygons.html">tm_borders</a></span><span class="op">(</span>col<span class="op">=</span><span class="st">"black"</span><span class="op">)</span><span class="op">+</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_shape.html">tm_shape</a></span><span class="op">(</span><span class="va">stdbcan.Bruit</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_symbols.html">tm_dots</a></span><span class="op">(</span>shape <span class="op">=</span> <span class="fl">21</span>, col<span class="op">=</span><span class="st">"black"</span>, size<span class="op">=</span><span class="fl">.2</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_shape.html">tm_shape</a></span><span class="op">(</span><span class="va">stdbcan.Agregats</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_symbols.html">tm_dots</a></span><span class="op">(</span>shape <span class="op">=</span> <span class="fl">21</span>, col<span class="op">=</span><span class="st">"stdbscan.1000_21"</span>, size<span class="op">=</span><span class="fl">.2</span>, title <span class="op">=</span> <span class="st">"Agrégat"</span><span class="op">)</span><span class="op">+</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_layout.html">tm_layout</a></span><span class="op">(</span>frame <span class="op">=</span> <span class="cn">FALSE</span>, legend.position <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"center"</span>, <span class="st">"bottom"</span><span class="op">)</span>,</span>
<span>          legend.text.size <span class="op">=</span> <span class="fl">.85</span>, legend.outside <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-CarteStScanEps1000Eps21" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="04-AgregatsSpatiaux_files/figure-html/fig-CarteStScanEps1000Eps21-1.png" class="img-fluid figure-img" style="width:65.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;4.11: Agrégats identifiés avec ST-DBSCAN</figcaption></figure>
</div>
</div>
</div>
</section></section></section><section id="sec-042" class="level2" data-number="4.2"><h2 data-number="4.2" class="anchored" data-anchor-id="sec-042">
<span class="header-section-number">4.2</span> Méthodes de balayage de Kulldorff</h2>
<section id="sec-0421" class="level3" data-number="4.2.1"><h3 data-number="4.2.1" class="anchored" data-anchor-id="sec-0421">
<span class="header-section-number">4.2.1</span> Objectifs de la méthode, types d’analyses, de modèles et d’agrégats</h3>
</section><section id="sec-0422" class="level3" data-number="4.2.2"><h3 data-number="4.2.2" class="anchored" data-anchor-id="sec-0422">
<span class="header-section-number">4.2.2</span> Principes de base de la méthode</h3>
<section id="sec-04221" class="level4" data-number="4.2.2.1"><h4 data-number="4.2.2.1" class="anchored" data-anchor-id="sec-04221">
<span class="header-section-number">4.2.2.1</span> Type de balayage (cercle ou ellipse)</h4>
</section><section id="sec-04222" class="level4" data-number="4.2.2.2"><h4 data-number="4.2.2.2" class="anchored" data-anchor-id="sec-04222">
<span class="header-section-number">4.2.2.2</span> Variable de contrôle</h4>
</section></section><section id="sec-043" class="level3" data-number="4.2.3"><h3 data-number="4.2.3" class="anchored" data-anchor-id="sec-043">
<span class="header-section-number">4.2.3</span> Mise en œuvre dans R</h3>
<section id="sec-0431" class="level4" data-number="4.2.3.1"><h4 data-number="4.2.3.1" class="anchored" data-anchor-id="sec-0431">
<span class="header-section-number">4.2.3.1</span> Agrégats temporels, spatiaux et spatio-temporels</h4>
</section><section id="sec-0432" class="level4" data-number="4.2.3.2"><h4 data-number="4.2.3.2" class="anchored" data-anchor-id="sec-0432">
<span class="header-section-number">4.2.3.2</span> Introduction de variables de contrôle</h4>
</section><section id="sec-0434" class="level4" data-number="4.2.3.3"><h4 data-number="4.2.3.3" class="anchored" data-anchor-id="sec-0434">
<span class="header-section-number">4.2.3.3</span> Exploration d’autres types de modèles</h4>
</section></section></section><section id="sec-044" class="level2" data-number="4.3"><h2 data-number="4.3" class="anchored" data-anchor-id="sec-044">
<span class="header-section-number">4.3</span> Quiz de révision du chapitre</h2>
<div id="Chap04" class="card">
<link type="text/javascript" src="libs/quizlib.1.0.1.min.js">
<script>var Quiz=function(a,b){this.Classes=Object.freeze({QUESTION:"quizlib-question",QUESTION_TITLE:"quizlib-question-title",QUESTION_ANSWERS:"quizlib-question-answers",QUESTION_WARNING:"quizlib-question-warning",CORRECT:"quizlib-correct",INCORRECT:"quizlib-incorrect",TEMP:"quizlib-temp"}),this.unansweredQuestionText="Question sans réponse !",this.container=document.getElementById(a),this.questions=[],this.result=new QuizResult,this.answers=b;for(var c=0;c<this.container.children.length;c++)this.container.children[c].classList.contains(Quiz.Classes.QUESTION)&&this.questions.push(this.container.children[c]);if(this.answers.length!=this.questions.length)throw new Error("Number of answers does not match number of questions!")};Quiz.Classes=Object.freeze({QUESTION:"quizlib-question",QUESTION_TITLE:"quizlib-question-title",QUESTION_ANSWERS:"quizlib-question-answers",QUESTION_WARNING:"quizlib-question-warning",CORRECT:"quizlib-correct",INCORRECT:"quizlib-incorrect",TEMP:"quizlib-temp"}),Quiz.prototype.checkAnswers=function(a){void 0===a&&(a=!0);for(var b=[],c=[],d=0;d<this.questions.length;d++){var e=this.questions[d],f=this.answers[d],g=[];this.clearHighlights(e);for(var h,i=e.getElementsByClassName(Quiz.Classes.QUESTION_ANSWERS)[0].getElementsByTagName("input"),j=0;j<i.length;j++)h=i[j],"checkbox"===h.type||"radio"===h.type?h.checked&&g.push(h.value):""!==h.value&&g.push(h.value);1!=g.length||Array.isArray(f)?0===g.length&&b.push(e):g=g[0],c.push(Utils.compare(g,f))}if(0===b.length||!a)return this.result.setResults(c),!0;for(d=0;d<b.length;d++){var k=document.createElement("span");k.appendChild(document.createTextNode(this.unansweredQuestionText)),k.className=Quiz.Classes.QUESTION_WARNING,b[d].getElementsByClassName(Quiz.Classes.QUESTION_TITLE)[0].appendChild(k)}return!1},Quiz.prototype.clearHighlights=function(a){for(var b=a.getElementsByClassName(Quiz.Classes.QUESTION_WARNING);b.length>0;)b[0].parentNode.removeChild(b[0]);var c,d=[a.getElementsByClassName(Quiz.Classes.CORRECT),a.getElementsByClassName(this.Classes.INCORRECT)];for(i=0;i<d.length;i++)for(;d[i].length>0;)c=d[i][0],c.classList.remove(Quiz.Classes.CORRECT),c.classList.remove(Quiz.Classes.INCORRECT);for(var e=a.getElementsByClassName(Quiz.Classes.TEMP);e.length>0;)e[0].parentNode.removeChild(e[0])},Quiz.prototype.highlightResults=function(a){for(var b,c=0;c<this.questions.length;c++)b=this.questions[c],b.getElementsByClassName(Quiz.Classes.QUESTION_TITLE)[0].classList.add(this.result.results[c]?Quiz.Classes.CORRECT:Quiz.Classes.INCORRECT),void 0!==a&&a(this,b,c,this.result.results[c])};var QuizResult=function(){this.results=[],this.totalQuestions=0,this.score=0,this.scorePercent=0,this.scorePercentFormatted=0};QuizResult.prototype.setResults=function(a){this.results=a,this.totalQuestions=this.results.length,this.score=0;for(var b=0;b<this.results.length;b++)this.results[b]&&this.score++;this.scorePercent=this.score/this.totalQuestions,this.scorePercentFormatted=Math.floor(100*this.scorePercent)};var Utils=function(){};Utils.compare=function(a,b){if(a.length!=b.length)return!1;if(Array.isArray(a)&&Array.isArray(b)){for(var c=0;c<a.length;c++)if(a[c]!==b[c])return!1;return!0}return a===b};

function showResults(quiz) {
    // Check answers and continue if all questions have been answered
    if (quiz.checkAnswers()) {
        var quizScorePercent = quiz.result.scorePercentFormatted; // The unformatted percentage is a decimal in range 0 - 1
        var quizResultElement = document.getElementById('quiz-result');
        quizResultElement.style.display = 'block';
        document.getElementById('quiz-percent').innerHTML = quizScorePercent.toString();

        // Change background colour of results div according to score percent
        if (quizScorePercent > 75) quizResultElement.style.backgroundColor = '#4caf50';
        else if (quizScorePercent > 50) quizResultElement.style.backgroundColor = '#ffc107';
        else if (quizScorePercent > 25) quizResultElement.style.backgroundColor = '#ff9800';
        else if (quizScorePercent > 0) quizResultElement.style.backgroundColor = '#f44336';

        // Highlight questions according to whether they were correctly answered. The callback allows us to highlight/show the correct answer
        quiz.highlightResults(handleAnswers);
    }
}

/** Callback for Quiz.highlightResults. Highlights the correct answers of incorrectly answered questions
 * Parameters are: the quiz object, the question element, question number, correctly answered flag
 */
function handleAnswers(quiz, question, no, correct) {
    if (!correct) {
        var answers = question.getElementsByTagName('input');
        for (var i = 0; i < answers.length; i++) {
            if (answers[i].type === 'checkbox' || answers[i].type === 'radio'){
                // If the current input element is part of the correct answer, highlight it
                if (quiz.answers[no].indexOf(answers[i].value) > -1) {
                    answers[i].parentNode.classList.add(Quiz.Classes.CORRECT);
                }
            } else {
                // If the input is anything other than a checkbox or radio button, show the correct answer next to the element
                var correctAnswer = document.createElement('span');
                correctAnswer.classList.add(Quiz.Classes.CORRECT);
                correctAnswer.classList.add(Quiz.Classes.TEMP); // quiz.checkAnswers will automatically remove elements with the temp class
                correctAnswer.innerHTML = quiz.answers[no];
                correctAnswer.style.marginLeft = '10px';
                answers[i].parentNode.insertBefore(correctAnswer, answers[i].nextSibling);
            }
        }
    }
}

  var quizz_Chap04;
  window.onload = function() {
    quizz_Chap04 = new Quiz('Chap04', ['2','2',['1', '3', '4'],['1', '2'],'1',['1', '2', '3']]);
  };</script><link rel="stylesheet" type="text/css" src="css/quizlib.min.css">
<div class="card quizlib-question">
<div class="quizlib-question-title">
L’algorithme DBSCAN est basé sur :
</div>
<div>
Relisez au besoin la <a href="#sec-04111">section&nbsp;<span>4.1.1.1</span></a>.
</div>
<div class="quizlib-question-answers">

<table class="table table-sm table-striped small">
<tbody><tr>
<td>
<label>La distance entre les points</label>
</td>
<td>
<input type="radio" name="q1" value="1">
</td>
</tr>
<tr>
<td>
<label>La densité des points</label>
</td>
<td>
<input type="radio" name="q1" value="2">
</td>
</tr>
</tbody></table>
</div>
</div>
<div class="card quizlib-question">
<div class="quizlib-question-title">
Avec l’algorithme DBSCAN, vous devez spécifier le nombre de groupes (agrégats).
</div>
<div>
Relisez au besoin la <a href="#sec-04111">section&nbsp;<span>4.1.1.1</span></a>.
</div>
<div class="quizlib-question-answers">

<table class="table table-sm table-striped small">
<tbody><tr>
<td>
<label>Vrai</label>
</td>
<td>
<input type="radio" name="q2" value="1">
</td>
</tr>
<tr>
<td>
<label>Faux</label>
</td>
<td>
<input type="radio" name="q2" value="2">
</td>
</tr>
</tbody></table>
</div>
</div>
<div class="card quizlib-question">
<div class="quizlib-question-title">
Quels sont les trois types de points identifiés par DBSCAN?
</div>
<div>
Relisez au besoin l’encadré à la <a href="#sec-04111">section&nbsp;<span>4.1.1.1</span></a>.
</div>
<div class="quizlib-question-answers">

<table class="table table-sm table-striped small">
<tbody><tr>
<td>
<label>Points centraux</label>
</td>
<td>
<input type="checkbox" name="q3" value="1">
</td>
</tr>
<tr>
<td>
<label>Points médians</label>
</td>
<td>
<input type="checkbox" name="q3" value="2">
</td>
</tr>
<tr>
<td>
<label>Points frontières</label>
</td>
<td>
<input type="checkbox" name="q3" value="3">
</td>
</tr>
<tr>
<td>
<label>Points aberrants</label>
</td>
<td>
<input type="checkbox" name="q3" value="4">
</td>
</tr>
</tbody></table>
</div>
</div>
<div class="card quizlib-question">
<div class="quizlib-question-title">
Quels sont les deux paramètres de l’algorithme DBSCAN?
</div>
<div>
Relisez au besoin la <a href="#sec-04111">section&nbsp;<span>4.1.1.1</span></a>.
</div>
<div class="quizlib-question-answers">

<table class="table table-sm table-striped small">
<tbody><tr>
<td>
<label>Le nombre de points minimum pour identifier les points centraux (MinPts)</label>
</td>
<td>
<input type="checkbox" name="q4" value="1">
</td>
</tr>
<tr>
<td>
<label>Le rayon de recherche (epsilon)</label>
</td>
<td>
<input type="checkbox" name="q4" value="2">
</td>
</tr>
<tr>
<td>
<label>La distance standard (DS)</label>
</td>
<td>
<input type="checkbox" name="q4" value="3">
</td>
</tr>
</tbody></table>
</div>
</div>
<div class="card quizlib-question">
<div class="quizlib-question-title">
Plus la valeur d’epsilon est grande, plus le nombre d’agrégats diminue.
</div>
<div>
Relisez au besoin la <a href="#sec-04112">section&nbsp;<span>4.1.1.2</span></a>.
</div>
<div class="quizlib-question-answers">

<table class="table table-sm table-striped small">
<tbody><tr>
<td>
<label>Vrai</label>
</td>
<td>
<input type="radio" name="q5" value="1">
</td>
</tr>
<tr>
<td>
<label>Faux</label>
</td>
<td>
<input type="radio" name="q5" value="2">
</td>
</tr>
</tbody></table>
</div>
</div>
<div class="card quizlib-question">
<div class="quizlib-question-title">
Quels sont les trois paramètres de l’algorithme ST-DBSCAN?
</div>
<div>
Relisez au besoin la <a href="#sec-0412">section&nbsp;<span>4.1.2</span></a>.
</div>
<div class="quizlib-question-answers">

<table class="table table-sm table-striped small">
<tbody><tr>
<td>
<label>Le nombre de points minimum pour identifier les points centraux (MinPts)</label>
</td>
<td>
<input type="checkbox" name="q6" value="1">
</td>
</tr>
<tr>
<td>
<label>Le rayon de recherche pour la proximité spatiale (eps1)</label>
</td>
<td>
<input type="checkbox" name="q6" value="2">
</td>
</tr>
<tr>
<td>
<label>Le rayon de recherche pour la proximité temporelle (eps2)</label>
</td>
<td>
<input type="checkbox" name="q6" value="3">
</td>
</tr>
<tr>
<td>
<label>La région d’étude</label>
</td>
<td>
<input type="checkbox" name="q6" value="4">
</td>
</tr>
</tbody></table>
</div>
</div>
<button type="button" onclick="showResults(quizz_Chap04);" id="buttonID">
Vérifier votre résultat
</button>
<div id="quiz-result" class="card">
<p><span id="quiz-percent"></span></p>
</div>
</div>
</section><section id="sec-045" class="level2" data-number="4.4"><h2 data-number="4.4" class="anchored" data-anchor-id="sec-045">
<span class="header-section-number">4.4</span> Exercices de révision</h2>
<div class="bloc_exercice">
<div class="bloc_exercice-header">
<div class="bloc_exercice-icon">

</div>
<p><strong>Exercice 1.</strong> Application de l’algorithme DBSCAN</p>
</div>
<div class="bloc_exercice-body">
<p>L’objectif est d’appliquer cet algorithme sur des accidents impliquant des personnes à vélo sur l’île de Montréal (voir la <a href="#sec-04141">section&nbsp;<span>4.1.3.1</span></a>). Ces données ouvertes sur les collisions routières et leur documentation sont disponibles au <a href="https://donnees.montreal.ca/dataset/collisions-routieres">lien suivant</a>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tmap)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dbscan)</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="do">## Importation des données</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>Collissions <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="at">dsn =</span> <span class="st">"data/chap04/collisions.gpkg"</span>, </span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>                       <span class="at">layer =</span> <span class="st">"CollisionsRoutieres"</span>, </span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>                       <span class="at">quiet =</span> <span class="cn">TRUE</span>)</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a><span class="do">## Collisions impliquant au moins une personne à vélo en 2020 et 2021</span></span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>Coll.Velo <span class="ot">&lt;-</span> <span class="fu">subset</span>(Collissions,</span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>                    Collissions<span class="sc">$</span>NB_VICTIMES_VELO <span class="sc">&gt;</span> <span class="dv">0</span> <span class="sc">&amp;</span></span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>                      Collissions<span class="sc">$</span>AN <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">2020</span>, <span class="dv">2021</span>))</span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a><span class="do">## Coordonnées géographiques</span></span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a>xy <span class="ot">&lt;-</span> <span class="fu">st_coordinates</span>(Coll.Velo)</span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a><span class="do">## Graphique pour la distance au quatrième voisin le plus proche</span></span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a>DistKplusproche <span class="ot">&lt;-</span> <span class="fu">kNNdist</span>(xy, <span class="at">k =</span> <span class="dv">4</span>)</span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a>DistKplusproche <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">sort</span>(DistKplusproche, <span class="at">decreasing =</span> <span class="cn">FALSE</span>))</span>
<span id="cb24-18"><a href="#cb24-18" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(DistKplusproche) <span class="ot">&lt;-</span> <span class="st">"distance"</span></span>
<span id="cb24-19"><a href="#cb24-19" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(à compléter)<span class="sc">+</span></span>
<span id="cb24-20"><a href="#cb24-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_path</span>(à compléter)<span class="sc">+</span></span>
<span id="cb24-21"><a href="#cb24-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(à compléter)<span class="sc">+</span></span>
<span id="cb24-22"><a href="#cb24-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept=</span><span class="dv">250</span>, <span class="at">color =</span> <span class="st">"#08306b"</span>, <span class="at">linetype=</span><span class="st">"dashed"</span>, <span class="at">size=</span><span class="dv">1</span>)<span class="sc">+</span></span>
<span id="cb24-23"><a href="#cb24-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept=</span><span class="dv">500</span>, <span class="at">color =</span> <span class="st">"#00441b"</span>, <span class="at">linetype=</span><span class="st">"dashed"</span>, <span class="at">size=</span><span class="dv">1</span>)<span class="sc">+</span></span>
<span id="cb24-24"><a href="#cb24-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept=</span><span class="dv">1000</span>, <span class="at">color =</span> <span class="st">"#67000d"</span>, <span class="at">linetype=</span><span class="st">"dashed"</span>, <span class="at">size=</span><span class="dv">1</span>)</span>
<span id="cb24-25"><a href="#cb24-25" aria-hidden="true" tabindex="-1"></a><span class="do">## DBSCAN avec les quatre distances</span></span>
<span id="cb24-26"><a href="#cb24-26" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123456789</span>)</span>
<span id="cb24-27"><a href="#cb24-27" aria-hidden="true" tabindex="-1"></a>dbscan250  <span class="ot">&lt;-</span> à compléter</span>
<span id="cb24-28"><a href="#cb24-28" aria-hidden="true" tabindex="-1"></a>dbscan500  <span class="ot">&lt;-</span> à compléter</span>
<span id="cb24-29"><a href="#cb24-29" aria-hidden="true" tabindex="-1"></a>dbscan1000 <span class="ot">&lt;-</span> à compléter</span>
<span id="cb24-30"><a href="#cb24-30" aria-hidden="true" tabindex="-1"></a><span class="do">## Affichage des résultats</span></span>
<span id="cb24-31"><a href="#cb24-31" aria-hidden="true" tabindex="-1"></a>dbscan250</span>
<span id="cb24-32"><a href="#cb24-32" aria-hidden="true" tabindex="-1"></a>dbscan500</span>
<span id="cb24-33"><a href="#cb24-33" aria-hidden="true" tabindex="-1"></a>dbscan1000</span>
<span id="cb24-34"><a href="#cb24-34" aria-hidden="true" tabindex="-1"></a><span class="do">## Enregistrement dans la couche de points sf Coll.Velo</span></span>
<span id="cb24-35"><a href="#cb24-35" aria-hidden="true" tabindex="-1"></a>Coll.Velo<span class="sc">$</span>dbscan250 <span class="ot">&lt;-</span> à compléter</span>
<span id="cb24-36"><a href="#cb24-36" aria-hidden="true" tabindex="-1"></a>Coll.Velo<span class="sc">$</span>dbscan500 <span class="ot">&lt;-</span> à compléter</span>
<span id="cb24-37"><a href="#cb24-37" aria-hidden="true" tabindex="-1"></a>Coll.Velo<span class="sc">$</span>dbscan1000 <span class="ot">&lt;-</span> à compléter</span>
<span id="cb24-38"><a href="#cb24-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-39"><a href="#cb24-39" aria-hidden="true" tabindex="-1"></a>Coll.Velo<span class="sc">$</span>dbscan250 <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(<span class="fu">nchar</span>(Coll.Velo<span class="sc">$</span>dbscan250) <span class="sc">==</span> <span class="dv">1</span>,</span>
<span id="cb24-40"><a href="#cb24-40" aria-hidden="true" tabindex="-1"></a>                              <span class="fu">paste0</span>(<span class="st">"0"</span>, Coll.Velo<span class="sc">$</span>dbscan250),</span>
<span id="cb24-41"><a href="#cb24-41" aria-hidden="true" tabindex="-1"></a>                              Coll.Velo<span class="sc">$</span>dbscan250)</span>
<span id="cb24-42"><a href="#cb24-42" aria-hidden="true" tabindex="-1"></a>Coll.Velo<span class="sc">$</span>dbscan500 <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(<span class="fu">nchar</span>(Coll.Velo<span class="sc">$</span>dbscan500) <span class="sc">==</span> <span class="dv">1</span>,</span>
<span id="cb24-43"><a href="#cb24-43" aria-hidden="true" tabindex="-1"></a>                               <span class="fu">paste0</span>(<span class="st">"0"</span>, Coll.Velo<span class="sc">$</span>dbscan500),</span>
<span id="cb24-44"><a href="#cb24-44" aria-hidden="true" tabindex="-1"></a>                               Coll.Velo<span class="sc">$</span>dbscan500)</span>
<span id="cb24-45"><a href="#cb24-45" aria-hidden="true" tabindex="-1"></a>Coll.Velo<span class="sc">$</span>dbscan1000 <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(<span class="fu">nchar</span>(Coll.Velo<span class="sc">$</span>dbscan1000) <span class="sc">==</span> <span class="dv">1</span>,</span>
<span id="cb24-46"><a href="#cb24-46" aria-hidden="true" tabindex="-1"></a>                               <span class="fu">paste0</span>(<span class="st">"0"</span>, Coll.Velo<span class="sc">$</span>dbscan1000),</span>
<span id="cb24-47"><a href="#cb24-47" aria-hidden="true" tabindex="-1"></a>                               Coll.Velo<span class="sc">$</span>dbscan1000)</span>
<span id="cb24-48"><a href="#cb24-48" aria-hidden="true" tabindex="-1"></a><span class="co"># Extraction des agrégats</span></span>
<span id="cb24-49"><a href="#cb24-49" aria-hidden="true" tabindex="-1"></a>Agregats.dbscan250  <span class="ot">&lt;-</span> <span class="fu">subset</span>(Coll.Velo, dbscan250 <span class="sc">!=</span> <span class="st">"00"</span>)</span>
<span id="cb24-50"><a href="#cb24-50" aria-hidden="true" tabindex="-1"></a>Agregats.dbscan500  <span class="ot">&lt;-</span> <span class="fu">subset</span>(Coll.Velo, dbscan500 <span class="sc">!=</span> <span class="st">"00"</span>)</span>
<span id="cb24-51"><a href="#cb24-51" aria-hidden="true" tabindex="-1"></a>Agregats.dbscan1000 <span class="ot">&lt;-</span> <span class="fu">subset</span>(Coll.Velo, dbscan1000 <span class="sc">!=</span> <span class="st">"00"</span>)</span>
<span id="cb24-52"><a href="#cb24-52" aria-hidden="true" tabindex="-1"></a><span class="do">## Cartographie</span></span>
<span id="cb24-53"><a href="#cb24-53" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb24-54"><a href="#cb24-54" aria-hidden="true" tabindex="-1"></a>à compléter</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Correction à la <a href="10-Exercices.html#sec-10041">section&nbsp;<span>9.4.1</span></a>.</p>
</div>
</div>
<div class="bloc_exercice">
<div class="bloc_exercice-header">
<div class="bloc_exercice-icon">

</div>
<p><strong>Exercice 2.</strong> Application de l’algorithme ST-DBSCAN</p>
</div>
<div class="bloc_exercice-body">
<p>Avec le même jeu de données, réaliser un ST-DBSCAN avec les paramètres suivants&nbsp;: distance spatiale de 500&nbsp;mètres, distance temporelle de&nbsp;30 jours et quatre points minimum (voir la <a href="#sec-04142">section&nbsp;<span>4.1.3.2</span></a>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tmap)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dbscan)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a><span class="do">## Importation des données</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>Collissions <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="at">dsn =</span> <span class="st">"data/chap04/collisions.gpkg"</span>, </span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>                       <span class="at">layer =</span> <span class="st">"CollisionsRoutieres"</span>,</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>                       <span class="at">quiet =</span> <span class="cn">TRUE</span>)</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a><span class="do">## Collisions impliquant au moins une personne à vélo en 2020 et 2021</span></span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>Coll.Velo <span class="ot">&lt;-</span> <span class="fu">subset</span>(Collissions,</span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>                    Collissions<span class="sc">$</span>NB_VICTIMES_VELO <span class="sc">&gt;</span> <span class="dv">0</span> <span class="sc">&amp;</span></span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>                      Collissions<span class="sc">$</span>AN <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">2020</span>, <span class="dv">2021</span>))</span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a><span class="do">## Coordonnées géographiques</span></span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>xy <span class="ot">&lt;-</span> <span class="fu">st_coordinates</span>(Coll.Velo)</span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a>Coll.Velo<span class="sc">$</span>x <span class="ot">&lt;-</span> xy[,<span class="dv">1</span>]</span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a>Coll.Velo<span class="sc">$</span>y <span class="ot">&lt;-</span> xy[,<span class="dv">2</span>]</span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a><span class="do">## Conversion du champ DT_ACCDN au format Date</span></span>
<span id="cb25-18"><a href="#cb25-18" aria-hidden="true" tabindex="-1"></a>Coll.Velo<span class="sc">$</span>DT_ACCDN <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(Coll.Velo<span class="sc">$</span>DT_ACCDN)</span>
<span id="cb25-19"><a href="#cb25-19" aria-hidden="true" tabindex="-1"></a><span class="do">## ST-DBSCAN avec eps1 = 500, esp2 = 30 et minpts = 4</span></span>
<span id="cb25-20"><a href="#cb25-20" aria-hidden="true" tabindex="-1"></a>Resultats.stdbscan <span class="ot">&lt;-</span> <span class="fu">stdbscan</span>(À compléter)</span>
<span id="cb25-21"><a href="#cb25-21" aria-hidden="true" tabindex="-1"></a><span class="do">## Enregistrement des résultats ST-DBSCAN dans la couche de points sf</span></span>
<span id="cb25-22"><a href="#cb25-22" aria-hidden="true" tabindex="-1"></a>Coll.Velo<span class="sc">$</span>stdbscan <span class="ot">&lt;-</span> <span class="fu">as.character</span>(Resultats.stdbscan<span class="sc">$</span>cluster)</span>
<span id="cb25-23"><a href="#cb25-23" aria-hidden="true" tabindex="-1"></a>Coll.Velo<span class="sc">$</span>stdbscan <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(<span class="fu">nchar</span>(Coll.Velo<span class="sc">$</span>stdbscan) <span class="sc">==</span> <span class="dv">1</span>,</span>
<span id="cb25-24"><a href="#cb25-24" aria-hidden="true" tabindex="-1"></a>                             <span class="fu">paste0</span>(<span class="st">"0"</span>, Coll.Velo<span class="sc">$</span>stdbscan),</span>
<span id="cb25-25"><a href="#cb25-25" aria-hidden="true" tabindex="-1"></a>                             Coll.Velo<span class="sc">$</span>stdbscan)</span>
<span id="cb25-26"><a href="#cb25-26" aria-hidden="true" tabindex="-1"></a><span class="do">## Nombre de points par agrégat avec la fonction table</span></span>
<span id="cb25-27"><a href="#cb25-27" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(Coll.Velo<span class="sc">$</span>stdbscan)</span>
<span id="cb25-28"><a href="#cb25-28" aria-hidden="true" tabindex="-1"></a><span class="do">## Sélection des points appartenant à un agrégat avec la fonction subset</span></span>
<span id="cb25-29"><a href="#cb25-29" aria-hidden="true" tabindex="-1"></a>Agregats <span class="ot">&lt;-</span> <span class="fu">subset</span>(Coll.Velo, stdbscan <span class="sc">!=</span> <span class="st">"00"</span>)</span>
<span id="cb25-30"><a href="#cb25-30" aria-hidden="true" tabindex="-1"></a><span class="do">## Conversion de la date au format POSIXct</span></span>
<span id="cb25-31"><a href="#cb25-31" aria-hidden="true" tabindex="-1"></a>Agregats<span class="sc">$</span>dtPOSIXct <span class="ot">&lt;-</span> <span class="fu">as.POSIXct</span>(Agregats<span class="sc">$</span>DT_ACCDN, <span class="at">format =</span> <span class="st">"%Y/%m/%d"</span>)</span>
<span id="cb25-32"><a href="#cb25-32" aria-hidden="true" tabindex="-1"></a><span class="do">## Tableau récapitulatif</span></span>
<span id="cb25-33"><a href="#cb25-33" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"dplyr"</span>)  </span>
<span id="cb25-34"><a href="#cb25-34" aria-hidden="true" tabindex="-1"></a>Tableau.stdbscan <span class="ot">&lt;-</span> À compléter</span>
<span id="cb25-35"><a href="#cb25-35" aria-hidden="true" tabindex="-1"></a><span class="do">## Affichage du tableau</span></span>
<span id="cb25-36"><a href="#cb25-36" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(Tableau.stdbscan, <span class="at">n =</span> <span class="fu">nrow</span>(Tableau.stdbscan))</span>
<span id="cb25-37"><a href="#cb25-37" aria-hidden="true" tabindex="-1"></a><span class="do">## Construction du graphique</span></span>
<span id="cb25-38"><a href="#cb25-38" aria-hidden="true" tabindex="-1"></a>À compléter</span>
<span id="cb25-39"><a href="#cb25-39" aria-hidden="true" tabindex="-1"></a><span class="do">## Création d'une couche pour les agrégats</span></span>
<span id="cb25-40"><a href="#cb25-40" aria-hidden="true" tabindex="-1"></a>stdbcan.Agregats <span class="ot">&lt;-</span> <span class="fu">subset</span>(Coll.Velo, stdbscan <span class="sc">!=</span> <span class="st">"00"</span>)</span>
<span id="cb25-41"><a href="#cb25-41" aria-hidden="true" tabindex="-1"></a><span class="do">## Cartographie</span></span>
<span id="cb25-42"><a href="#cb25-42" aria-hidden="true" tabindex="-1"></a>À compléter</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Correction à la <a href="10-Exercices.html#sec-10042">section&nbsp;<span>9.4.2</span></a>.</p>
</div>
</div>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-birant2007st" class="csl-entry" role="listitem">
Birant, Derya et Alp Kut. 2007. <span>«&nbsp;ST-DBSCAN: An algorithm for clustering spatial–temporal data.&nbsp;»</span> <em>Data &amp; knowledge engineering</em> 60 (1): 208‑221. <a href="https://doi.org/10.1016/j.datak.2006.01.013">https://doi.org/10.1016/j.datak.2006.01.013</a>.
</div>
<div id="ref-HDBSCAN2013" class="csl-entry" role="listitem">
Campello, Ricardo JGB, Davoud Moulavi et Jörg Sander. 2013. <span>«&nbsp;Density-based clustering based on hierarchical density estimates.&nbsp;»</span> In <em>Advances in Knowledge Discovery and Data Mining: 17th Pacific-Asia Conference, PAKDD 2013, Gold Coast, Australia, April 14-17, 2013, Proceedings, Part II 17</em>, 160‑172. s.n. <a href="http://dx.doi.org/10.1007/978-3-642-37456-2_14">http://dx.doi.org/10.1007/978-3-642-37456-2_14</a>.
</div>
<div id="ref-DBSCAN1996" class="csl-entry" role="listitem">
Ester, Martin, Hans-Peter Kriegel, Jörg Sander et Xiaowei Xu. 1996. <span>«&nbsp;A density-based algorithm for discovering clusters in large spatial databases with noise.&nbsp;»</span> In <em>Proceedings of the Second International Conference on Knowledge Discovery and Data Mining (KDD-96)</em>, 96:226‑231. 34. s.n. <a href="https://dl.acm.org/doi/10.5555/3001460.3001507">https://dl.acm.org/doi/10.5555/3001460.3001507</a>.
</div>
<div id="ref-dbscanPackage1" class="csl-entry" role="listitem">
Hahsler, Michael et Matthew Piekenbrock. 2022. <em>dbscan: Density-Based Spatial Clustering of Applications with Noise (DBSCAN) and Related Algorithms</em>. s.n. <a href="https://CRAN.R-project.org/package=dbscan">https://CRAN.R-project.org/package=dbscan</a>.
</div>
<div id="ref-dbscanPackage2" class="csl-entry" role="listitem">
Hahsler, Michael, Matthew Piekenbrock et Derek Doran. 2019. <span>«&nbsp;<span>dbscan</span>: Fast Density-Based Clustering with <span>R</span>.&nbsp;»</span> <em>Journal of Statistical Software</em> 91 (1): 1‑30. <a href="https://doi.org/10.18637/jss.v091.i01">https://doi.org/10.18637/jss.v091.i01</a>.
</div>
<div id="ref-kulldorff1997spatial" class="csl-entry" role="listitem">
Kulldorff, Martin. 1997. <span>«&nbsp;A spatial scan statistic.&nbsp;»</span> <em>Communications in Statistics-Theory and methods</em> 26 (6): 1481‑1496. <a href="https://doi.org/10.1080/03610929708831995">https://doi.org/10.1080/03610929708831995</a>.
</div>
<div id="ref-sander1998density" class="csl-entry" role="listitem">
Sander, Jörg, Martin Ester, Hans-Peter Kriegel et Xiaowei Xu. 1998. <span>«&nbsp;Density-based clustering in spatial databases: The algorithm gdbscan and its applications.&nbsp;»</span> <em>Data mining and knowledge discovery</em> 2: 169‑194. <a href="https://doi.org/10.1023/A:1009745219419">https://doi.org/10.1023/A:1009745219419</a>.
</div>
</div>
</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copié");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copié");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./03-MethodesRepartitionPonctuelle.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Méthodes de répartition ponctuelle</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./05-AnalyseReseau.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Mesures d’accessibilité spatiale selon différents modes de transport</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">Méthodes d’analyse spatiale : un grand bol d’R.</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">Ce livre a été réalisé avec <a href="https://quarto.org/">Quarto</a>.</div>
  </div>
</footer>


</body></html>